apiVersion: v1
kind: Service
metadata:
  # the name should be aligned with the application.properties
  name: vprodb
spec:
  ports:
  - port: 3306
    targetPort: vprodb-port
    protocol: TCP
  selector:
    app: vprodb
  type: ClusterIP