apiVersion: v1
kind: Service
metadata:
  # the name should be aligned with the application.properties
  name: vprodb
spec:
  ports:
  - port: 3306
    targetPort: k8s-app-db-port
    protocol: TCP
  selectors:
    app: k8s-app-db
