apiVersion: apps/v1
kind: Deployment
metadata:
  name: vproapp
spec:
  selector:
    matchLabels:
      app: vproapp
  replicas: 1
  template:
    metadata:
      labels:
        app: vproapp
    spec:
      containers:
      - name: vproapp
        image: vprofile/vprofileapp:V1
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        ports:
        - containerPort: 8080
          name: vproapp-port
      # this init container is to prepare for the lauch of the main container
      initContainers:
        - name: init-mydb
          image: busybox:latest
          command: ["sh", "-c", "until nslookup vprodb; do echo waiting for mydb; sleep 2; done;"]
        - name: init-memcached
          image: busybox:latest
          command: ["sh", "-c", "until nslookup vprocache01; do echo waiting for memcached; sleep 2; done;"]