apiVersion: v1
kind: Service
metadata:
# this service name is aligned with the name in the application.properties file.
  name: vprocache01
spec:
  selector:
    app: vprocache01
  ports:
    - port: 11211
      targetPort: vprocache01-port
      protocol: TCP
  type: ClusterIP
